
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from main import calq


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Manue\Desktop\pycalq\assets\frame0")
o = False
n1 = int(0)
n2 = int(1)
op = '+'

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)
def number(t):
    if o == False:
        n1 = t
    elif o == True:
        n2 = t
def operacao(t):
    o = True
    op = t
def fim():
    calq(n1, op, n2)

window = Tk()

window.geometry("256x363")
window.configure(bg = "#0E1016")


canvas = Canvas(
    window,
    bg = "#0E1016",
    height = 363,
    width = 256,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    256.0,
    85.0,
    fill="#181A20",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command = number(1),
    relief="flat",
    background="#0E1016"
)
button_1.place(
    x=20.0,
    y=226.0,
    width=45.0,
    height=45.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=calq,
    relief="flat",
    background="#0E1016"
)
button_2.place(
    x=76.0,
    y=226.0,
    width=45.0,
    height=45.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
    background="#0E1016"
)
button_3.place(
    x=132.0,
    y=226.0,
    width=45.0,
    height=45.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat",
    background="#0E1016"
)
button_4.place(
    x=20.0,
    y=164.0,
    width=45.0,
    height=45.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat",
    background="#0E1016"
)
button_5.place(
    x=76.0,
    y=164.0,
    width=45.0,
    height=45.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat",
    background="#0E1016"
)
button_6.place(
    x=132.0,
    y=164.0,
    width=45.0,
    height=45.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat",
    background="#0E1016"
)
button_7.place(
    x=20.0,
    y=102.0,
    width=45.0,
    height=45.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat",
    background="#0E1016"
)
button_8.place(
    x=76.0,
    y=102.0,
    width=45.0,
    height=45.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat",
    background="#0E1016"
)
button_9.place(
    x=132.0,
    y=102.0,
    width=45.0,
    height=45.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat",
    background="#0E1016"
)
button_10.place(
    x=76.0,
    y=288.0,
    width=45.0,
    height=45.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat",
    background="#0E1016"
)
button_11.place(
    x=20.0,
    y=288.0,
    width=45.0,
    height=45.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat",
    background="#181A20"
)
button_12.place(
    x=212.0,
    y=30.25,
    width=24.0,
    height=16.01103973388672
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=operacao('+'),
    relief="flat",
    background="#0E1016"
)
button_13.place(
    x=188.0,
    y=102.0,
    width=45.0,
    height=45.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_14 clicked"),
    relief="flat",
    background="#0E1016"
)
button_14.place(
    x=188.0,
    y=164.0,
    width=45.0,
    height=45.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_15 clicked"),
    relief="flat",
    background="#0E1016"
)
button_15.place(
    x=188.0,
    y=226.0,
    width=45.0,
    height=45.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_16 clicked"),
    relief="flat",
    background="#0E1016"
)
button_16.place(
    x=188.0,
    y=288.0,
    width=45.0,
    height=45.0
)

button_image_17 = PhotoImage(
    file=relative_to_assets("button_17.png"))
button_17 = Button(
    image=button_image_17,
    borderwidth=0,
    highlightthickness=0,
    command=fim(),
    relief="flat",
    background="#0E1016"
)
button_17.place(
    x=132.0,
    y=288.0,
    width=45.0,
    height=45.0
)
canvas.create_text(
    20.0,
    30.0,
    anchor="nw",
    text='calq',
    fill="#FFFFFF",
    font=("JetBrainsMonoRoman Regular", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
